# Generated by Django 6.0.6 on 2026-06-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('entity_type', models.CharField(choices=[('city_government', 'City Government'), ('county_government', 'County Government'), ('workforce_development_board', 'Workforce Development Board'), ('economic_development_agency', 'Economic Development Agency'), ('public_school_district', 'Public School District'), ('public_library', 'Public Library'), ('housing_community_development_agency', 'Housing / Community Development Agency'), ('regional_planning_agency', 'Regional Planning Agency'), ('other', 'Other')], default='other', max_length=60)),
                ('geography', models.JSONField(blank=True, default=list)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('department_or_office', models.CharField(blank=True, default='', max_length=300)),
                ('opportunity_lanes', models.JSONField(blank=True, default=list)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Government entities',
            },
        ),
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('partner_type', models.CharField(choices=[('nonprofit', 'Nonprofit'), ('university_college', 'University / College'), ('community_college', 'Community College'), ('workforce_board', 'Workforce Board'), ('local_government_agency', 'Local Government Agency'), ('public_library', 'Public Library'), ('school_district', 'School District'), ('healthcare_organization', 'Healthcare Organization'), ('corporate_partner', 'Corporate Partner'), ('foundation', 'Foundation'), ('faith_based_organization', 'Faith-Based Organization'), ('community_based_organization', 'Community-Based Organization'), ('other', 'Other')], default='other', max_length=60)),
                ('geography', models.JSONField(blank=True, default=list)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('beneficiaries', models.JSONField(blank=True, default=list)),
                ('collaboration_opportunities', models.JSONField(blank=True, default=list)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('resource_type', models.CharField(choices=[('technical_assistance_provider', 'Technical Assistance Provider'), ('capacity_building_organization', 'Capacity Building Organization'), ('nonprofit_support_center', 'Nonprofit Support Center'), ('volunteer_network', 'Volunteer Network'), ('americorps_national_service', 'AmeriCorps / National Service'), ('university_program', 'University Program'), ('software_donation_program', 'Software Donation Program'), ('shared_services_provider', 'Shared Services Provider'), ('equipment_assistance_program', 'Equipment Assistance Program'), ('broadband_digital_access_program', 'Broadband / Digital Access Program'), ('other', 'Other')], default='other', max_length=60)),
                ('geography', models.JSONField(blank=True, default=list)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('resource_categories', models.JSONField(blank=True, default=list)),
                ('eligibility_notes', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='funder',
            name='description',
        ),
        migrations.AddField(
            model_name='funder',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='funder',
            name='beneficiaries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='funder',
            name='eligibility_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='funder',
            name='focus_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='funder',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='funder',
            name='funder_type',
            field=models.CharField(choices=[('community_foundation', 'Community Foundation'), ('corporate_foundation', 'Corporate Foundation'), ('family_foundation', 'Family Foundation'), ('federal_government', 'Federal Government'), ('state_government', 'State Government'), ('local_government', 'Local Government'), ('united_way', 'United Way'), ('workforce_board', 'Workforce Board'), ('other', 'Other')], default='other', max_length=40),
        ),
    ]
