# Generated by Django 6.0.6 on 2026-06-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_governmententity_partnerorganization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('opportunity_type', models.CharField(choices=[('grant', 'Grant'), ('contract', 'Contract'), ('partnership', 'Partnership'), ('resource', 'Resource'), ('sponsorship', 'Sponsorship'), ('training', 'Training'), ('capacity_building', 'Capacity Building')], default='grant', max_length=40)),
                ('source_type', models.CharField(choices=[('funder', 'Funder'), ('government', 'Government'), ('resource_provider', 'Resource Provider'), ('partner', 'Partner'), ('manual', 'Manual')], default='manual', max_length=40)),
                ('source_name', models.CharField(blank=True, default='', max_length=500)),
                ('geography', models.JSONField(blank=True, default=list)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('beneficiaries', models.JSONField(blank=True, default=list)),
                ('eligibility_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming'), ('archived', 'Archived')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
