# Generated by Django 6.0.6 on 2026-06-17 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('organization_type', models.CharField(choices=[('foundation', 'Foundation'), ('government_agency', 'Government Agency'), ('resource_provider', 'Resource Provider'), ('nonprofit', 'Nonprofit'), ('corporate_partner', 'Corporate Partner'), ('university', 'University'), ('workforce_board', 'Workforce Board'), ('other', 'Other')], default='other', max_length=40)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('geography', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='priority_level',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming'), ('monitoring', 'Monitoring'), ('applied', 'Applied'), ('won', 'Won'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='funding.sourceorganization'),
        ),
    ]
