# Generated by Django 6.0.6 on 2026-06-17 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_sourceorganization_opportunity_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='assigned_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lifecycle_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lifecycle_status',
            field=models.CharField(choices=[('discovered', 'Discovered'), ('reviewing', 'Reviewing'), ('qualified', 'Qualified'), ('pursuing', 'Pursuing'), ('application_drafting', 'Application Drafting'), ('submitted', 'Submitted'), ('awarded', 'Awarded'), ('declined', 'Declined'), ('closed', 'Closed')], default='discovered', max_length=40),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lifecycle_status_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
