# Generated by Django 6.0.6 on 2026-06-17 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0005_opportunity_assigned_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('deadline_date', models.DateField()),
                ('deadline_type', models.CharField(choices=[('submission', 'Submission'), ('internal_review', 'Internal Review'), ('budget', 'Budget'), ('narrative', 'Narrative'), ('attachments', 'Attachments'), ('follow_up', 'Follow-up'), ('reporting', 'Reporting')], default='submission', max_length=30)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('due_soon', 'Due Soon'), ('overdue', 'Overdue'), ('complete', 'Complete')], default='upcoming', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='funding.opportunity')),
            ],
            options={
                'ordering': ('deadline_date', 'title'),
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'title'), name='unique_opportunity_deadline_title')],
            },
        ),
        migrations.CreateModel(
            name='OpportunityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='funding.opportunity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', 'due_date', 'title'),
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'title'), name='unique_opportunity_task_title')],
            },
        ),
    ]
