# Generated by Django 6.0.6 on 2026-06-18 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_budget_range_and_more'),
        ('funding', '0006_opportunitydeadline_opportunitytask'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVaultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('document_type', models.CharField(choices=[('irs_determination_letter', 'IRS Determination Letter'), ('w9', 'W-9'), ('annual_budget', 'Annual Budget'), ('program_budget', 'Program Budget'), ('board_list', 'Board List'), ('strategic_plan', 'Strategic Plan'), ('annual_report', 'Annual Report'), ('outcome_report', 'Outcome Report'), ('audit_financial_statement', 'Audit / Financial Statement'), ('insurance', 'Insurance'), ('policy_document', 'Policy Document'), ('other', 'Other')], default='other', max_length=40)),
                ('status', models.CharField(choices=[('available', 'Available'), ('needs_update', 'Needs Update'), ('missing', 'Missing'), ('archived', 'Archived')], default='missing', max_length=20)),
                ('file_reference', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_vault_items', to='core.project')),
            ],
            options={
                'ordering': ('document_type', 'title'),
            },
        ),
        migrations.CreateModel(
            name='EvidenceLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('evidence_type', models.CharField(choices=[('outcome_metric', 'Outcome Metric'), ('impact_story', 'Impact Story'), ('evaluation_report', 'Evaluation Report'), ('testimonial', 'Testimonial'), ('community_need_data', 'Community Need Data'), ('program_result', 'Program Result'), ('partner_letter', 'Partner Letter'), ('media_mention', 'Media Mention'), ('other', 'Other')], default='other', max_length=40)),
                ('related_program', models.CharField(blank=True, default='', max_length=300)),
                ('metric_name', models.CharField(blank=True, default='', max_length=200)),
                ('metric_value', models.CharField(blank=True, default='', max_length=200)),
                ('evidence_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('available', 'Available'), ('needs_update', 'Needs Update'), ('missing', 'Missing'), ('archived', 'Archived')], default='missing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_library_items', to='core.project')),
            ],
            options={
                'ordering': ('evidence_type', 'title'),
            },
        ),
        migrations.CreateModel(
            name='OpportunityDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('requirement_type', models.CharField(choices=[('required_document', 'Required Document'), ('supporting_evidence', 'Supporting Evidence'), ('financial_document', 'Financial Document'), ('program_evidence', 'Program Evidence'), ('partnership_evidence', 'Partnership Evidence'), ('compliance_document', 'Compliance Document'), ('other', 'Other')], default='required_document', max_length=40)),
                ('status', models.CharField(choices=[('available', 'Available'), ('missing', 'Missing'), ('needs_update', 'Needs Update'), ('not_required', 'Not Required')], default='missing', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_requirements', to='funding.documentvaultitem')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='funding.opportunity')),
            ],
            options={
                'ordering': ('requirement_type', 'title'),
            },
        ),
        migrations.AddConstraint(
            model_name='documentvaultitem',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='unique_project_document_title'),
        ),
        migrations.AddConstraint(
            model_name='evidencelibraryitem',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='unique_project_evidence_title'),
        ),
        migrations.AddConstraint(
            model_name='opportunitydocumentrequirement',
            constraint=models.UniqueConstraint(fields=('opportunity', 'title'), name='unique_opportunity_document_requirement'),
        ),
    ]
