# Generated by Django 6.0.6 on 2026-06-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0007_documentvaultitem_evidencelibraryitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='forecast_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='value_confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
    ]
