# Generated by Django 6.0.6 on 2026-06-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0008_opportunity_estimated_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funder',
            name='intelligence_status',
            field=models.CharField(choices=[('active', 'Active'), ('monitoring', 'Monitoring'), ('prospect', 'Prospect'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='funder',
            name='source_references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='intelligence_status',
            field=models.CharField(choices=[('active', 'Active'), ('monitoring', 'Monitoring'), ('prospect', 'Prospect'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='mission_alignment_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='opportunity_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='relationship_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='source_references',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
