# Generated by Django 6.0.6 on 2026-06-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0009_funder_intelligence_status_funder_source_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funder',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funder',
            name='source_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='funder',
            name='source_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='funder',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('needs_review', 'Needs Review'), ('reviewed', 'Reviewed'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('needs_review', 'Needs Review'), ('reviewed', 'Reviewed'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='source_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='source_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('needs_review', 'Needs Review'), ('reviewed', 'Reviewed'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='sourceorganization',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceorganization',
            name='source_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sourceorganization',
            name='source_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sourceorganization',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('needs_review', 'Needs Review'), ('reviewed', 'Reviewed'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
    ]
