# Generated by Django 6.0.6 on 2026-06-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0011_opportunity_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming'), ('monitoring', 'Monitoring'), ('applied', 'Applied'), ('won', 'Won'), ('expired', 'Expired'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
