# Generated by Django 6.0.6 on 2026-06-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0012_alter_opportunity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
