# Generated by Django 6.0.6 on 2026-06-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0013_opportunity_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='interest_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_interested',
            field=models.BooleanField(default=False),
        ),
    ]
