# Generated by Django 6.0.6 on 2026-07-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0014_opportunity_interest_marked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='applicant_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
