# Generated by Django 6.0.6 on 2026-07-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0015_opportunity_applicant_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprovider',
            name='cost',
            field=models.CharField(choices=[('free', 'Free'), ('low_cost', 'Low-cost'), ('paid', 'Paid')], default='low_cost', max_length=20),
        ),
    ]
