# Generated by Django 6.0.6 on 2026-07-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0016_resourceprovider_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundationGrantPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filer_ein', models.CharField(db_index=True, max_length=9)),
                ('filer_name', models.CharField(blank=True, default='', max_length=500)),
                ('filer_city', models.CharField(blank=True, default='', max_length=120)),
                ('filer_state', models.CharField(blank=True, db_index=True, default='', max_length=2)),
                ('recipient_name', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('recipient_ein', models.CharField(blank=True, db_index=True, default='', max_length=9)),
                ('recipient_city', models.CharField(blank=True, default='', max_length=120)),
                ('recipient_state', models.CharField(blank=True, db_index=True, default='', max_length=2)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, default='')),
                ('tax_year', models.CharField(blank=True, db_index=True, default='', max_length=4)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('dedup_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foundation grant paid',
                'verbose_name_plural': 'Foundation grants paid',
                'indexes': [models.Index(fields=['filer_ein', 'tax_year'], name='funding_fgp_filer_year_idx')],
            },
        ),
    ]
