# Generated by Django 6.0.6 on 2026-07-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0017_foundationgrantpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='funder',
            name='grant_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='funder',
            name='grants_total_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='funder',
            name='is_derived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
