# Generated by Django 6.0.6 on 2026-08-02 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_excluded_beneficiaries'),
        ('funding', '0018_funder_grant_count_funder_grants_total_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('funder_name', models.CharField(blank=True, default='', max_length=500)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('drafting', 'Drafting'), ('needs_information', 'Needs Information'), ('ready_for_review', 'Ready for Review'), ('final_review', 'Final Review'), ('submitted', 'Submitted'), ('awarded', 'Awarded'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='not_started', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grant_applications', to=settings.AUTH_USER_MODEL)),
                ('funding_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_applications', to='funding.fundingsignal')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_applications', to='funding.opportunity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_applications', to='core.project')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='GrantApplicationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('funder_question', models.TextField(blank=True, default='')),
                ('guidance', models.JSONField(blank=True, default=list)),
                ('draft_response', models.TextField(blank=True, default='')),
                ('approved_response', models.TextField(blank=True, default='')),
                ('word_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('character_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('needs_information', 'Needs Information'), ('drafted', 'Drafted'), ('approved', 'Approved')], default='not_started', max_length=30)),
                ('source_fields', models.JSONField(blank=True, default=list)),
                ('missing_information', models.JSONField(blank=True, default=list)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='grants.grantapplication')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_grant_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='GrantAnswerLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mission', 'Mission'), ('organization_history', 'Organization History'), ('organization_overview', 'Organizational Overview'), ('statement_of_need', 'Statement of Need'), ('population_served', 'Population Served'), ('program_description', 'Program Description'), ('goals', 'Goals'), ('outcomes', 'Outcomes'), ('evaluation_approach', 'Evaluation Approach'), ('organizational_capacity', 'Organizational Capacity'), ('partnerships', 'Partnerships'), ('sustainability', 'Sustainability'), ('equity_inclusion', 'Equity / Inclusion Statement'), ('community_engagement', 'Community Engagement'), ('past_performance', 'Past Performance'), ('budget_narrative', 'Budget Narrative'), ('general_operating_support', 'General Operating Support'), ('implementation_plan', 'Implementation Plan'), ('other', 'Other')], default='other', max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('draft', 'Draft'), ('archived', 'Archived')], default='approved', max_length=20)),
                ('source_grant_title', models.CharField(blank=True, default='', max_length=500)),
                ('source_fields', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grant_answers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_answer_library', to='core.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_answer_library', to='core.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_grant_answers', to=settings.AUTH_USER_MODEL)),
                ('source_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items', to='grants.grantapplication')),
                ('source_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items', to='grants.grantapplicationsection')),
            ],
            options={
                'ordering': ('category', '-updated_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='grantapplication',
            constraint=models.UniqueConstraint(fields=('project', 'opportunity'), name='unique_project_opportunity_grant_application'),
        ),
        migrations.AddConstraint(
            model_name='grantapplicationsection',
            constraint=models.UniqueConstraint(fields=('application', 'section_key'), name='unique_application_section_key'),
        ),
        migrations.AddIndex(
            model_name='grantanswerlibraryitem',
            index=models.Index(fields=['organization', 'category'], name='grants_lib_org_cat_idx'),
        ),
    ]
