# Generated by Django 6.0.6 on 2026-08-02 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0018_funder_grant_count_funder_grants_total_amount_and_more'),
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplicationsection',
            name='attachment_requirement',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='grantapplicationsection',
            name='imported_label',
            field=models.CharField(blank=True, default='', help_text="The funder's own numbering, e.g. '3' or 'B.2'.", max_length=40),
        ),
        migrations.AddField(
            model_name='grantapplicationsection',
            name='imported_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grantapplicationsection',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='grantapplicationsection',
            name='original_question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='grantapplicationsection',
            name='page_limit_note',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='grantapplicationsection',
            name='question_type',
            field=models.CharField(choices=[('narrative', 'Narrative'), ('short_text', 'Short text'), ('long_text', 'Long text'), ('numeric', 'Numeric'), ('currency', 'Currency'), ('date', 'Date'), ('yes_no', 'Yes / No'), ('multiple_choice', 'Multiple choice'), ('attachment', 'Attachment'), ('informational', 'Informational'), ('unknown', 'Unknown')], default='narrative', max_length=20),
        ),
        migrations.AddField(
            model_name='grantapplicationsection',
            name='scoring_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='grantapplicationsection',
            name='section_group',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='grantapplicationsection',
            name='source_type',
            field=models.CharField(choices=[('template', 'Atlas standard template'), ('imported', 'Imported from the real application'), ('manual', 'Added by hand')], default='template', max_length=20),
        ),
        migrations.CreateModel(
            name='GrantApplicationImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('source_label', models.CharField(blank=True, default='', help_text="Where the text came from, e.g. 'Foundation portal, Section 2'.", max_length=300)),
                ('application_instructions', models.JSONField(blank=True, default=list)),
                ('parse_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('parse_notes', models.JSONField(blank=True, default=list)),
                ('detected_question_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('parsed', 'Parsed — awaiting review'), ('saved', 'Saved to application'), ('discarded', 'Discarded')], default='parsed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='grants.grantapplication')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_application_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='grantapplicationsection',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='grants.grantapplicationimport'),
        ),
        migrations.CreateModel(
            name='GrantAttachmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('document_type', models.CharField(choices=[('irs_determination_letter', 'IRS Determination Letter'), ('w9', 'W-9'), ('annual_budget', 'Annual Budget'), ('program_budget', 'Program Budget'), ('board_list', 'Board List'), ('strategic_plan', 'Strategic Plan'), ('annual_report', 'Annual Report'), ('outcome_report', 'Outcome Report'), ('audit_financial_statement', 'Audit / Financial Statement'), ('insurance', 'Insurance'), ('policy_document', 'Policy Document'), ('other', 'Other')], default='other', max_length=40)),
                ('confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_requirements', to='grants.grantapplication')),
                ('linked_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_attachment_requirements', to='funding.documentvaultitem')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_requirements', to='grants.grantapplicationimport')),
            ],
            options={
                'ordering': ('order', 'title'),
                'constraints': [models.UniqueConstraint(fields=('application', 'title'), name='unique_application_attachment_title')],
            },
        ),
    ]
