# Generated by Django 6.0.6 on 2026-06-18 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_budget_range_and_more'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('celebration_type', models.CharField(choices=[('opportunity_awarded', 'Opportunity Awarded'), ('opportunity_submitted', 'Opportunity Submitted'), ('partnership_formed', 'Partnership Formed'), ('program_launch', 'Program Launch'), ('funding_secured', 'Funding Secured'), ('impact_milestone', 'Impact Milestone'), ('volunteer_milestone', 'Volunteer Milestone'), ('organization_milestone', 'Organization Milestone'), ('success_story', 'Success Story'), ('community_achievement', 'Community Achievement')], default='organization_milestone', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('impact', models.TextField(blank=True, default='')),
                ('organization_name', models.CharField(blank=True, default='', max_length=300)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrations', to='core.project')),
            ],
            options={
                'ordering': ('-created_at', 'title'),
                'constraints': [models.UniqueConstraint(fields=('project', 'title'), name='unique_project_celebration_title')],
            },
        ),
    ]
