# Generated by Django 6.0.6 on 2026-06-18 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_budget_range_and_more'),
        ('signals', '0002_celebration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebration',
            name='celebration_type',
            field=models.CharField(choices=[('opportunity_awarded', 'Opportunity Awarded'), ('opportunity_submitted', 'Opportunity Submitted'), ('partnership_formed', 'Partnership Formed'), ('program_launch', 'Program Launch'), ('funding_secured', 'Funding Secured'), ('impact_milestone', 'Impact Milestone'), ('volunteer_milestone', 'Volunteer Milestone'), ('organization_milestone', 'Organization Milestone'), ('strategic_introduction', 'Strategic Introduction'), ('community_collaboration', 'Community Collaboration'), ('success_story', 'Success Story'), ('community_achievement', 'Community Achievement')], default='organization_milestone', max_length=40),
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('organization', models.CharField(blank=True, default='', max_length=300)),
                ('contact_type', models.CharField(choices=[('funder', 'Funder'), ('program_officer', 'Program Officer'), ('government_contact', 'Government Contact'), ('partner', 'Partner'), ('community_leader', 'Community Leader'), ('volunteer_leader', 'Volunteer Leader'), ('corporate_contact', 'Corporate Contact'), ('consultant', 'Consultant'), ('other', 'Other')], default='other', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=60)),
                ('notes', models.TextField(blank=True, default='')),
                ('relationship_strength', models.CharField(choices=[('unknown', 'Unknown'), ('weak', 'Weak'), ('developing', 'Developing'), ('established', 'Established'), ('strong', 'Strong')], default='unknown', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_contacts', to='core.project')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('project', 'name', 'organization'), name='unique_project_contact')],
            },
        ),
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=300)),
                ('partner_type', models.CharField(choices=[('funding_partner', 'Funding Partner'), ('community_partner', 'Community Partner'), ('government_partner', 'Government Partner'), ('corporate_partner', 'Corporate Partner'), ('academic_partner', 'Academic Partner'), ('service_partner', 'Service Partner'), ('advocacy_partner', 'Advocacy Partner'), ('other', 'Other')], default='other', max_length=40)),
                ('relationship_strength', models.CharField(choices=[('unknown', 'Unknown'), ('weak', 'Weak'), ('developing', 'Developing'), ('established', 'Established'), ('strong', 'Strong')], default='unknown', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_partners', to='core.project')),
            ],
            options={
                'ordering': ('organization_name',),
                'constraints': [models.UniqueConstraint(fields=('project', 'organization_name'), name='unique_project_relationship_partner')],
            },
        ),
    ]
