# Generated by Django 6.0.6 on 2026-06-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_alter_celebration_celebration_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('organization', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, default='', max_length=300)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('interest_type', models.CharField(choices=[('opportunity_web_snapshot', 'Get Opportunity Web Snapshot'), ('founding_atlas_partners', 'Join Founding Atlas Partners'), ('newsletter_updates', 'Newsletter / Updates'), ('partnership_inquiry', 'Partnership Inquiry')], default='opportunity_web_snapshot', max_length=40)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', 'organization', 'name'),
            },
        ),
    ]
