# Generated by Django 6.0.6 on 2026-06-21 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_budget_range_and_more'),
        ('signals', '0004_interestsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=300)),
                ('contact_name', models.CharField(blank=True, default='', max_length=300)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('lifecycle_status', models.CharField(choices=[('waitlist', 'Waitlist'), ('qualified', 'Qualified'), ('invited', 'Invited'), ('questionnaire_sent', 'Discovery Questionnaire Sent'), ('questionnaire_completed', 'Discovery Questionnaire Completed'), ('snapshot_in_progress', 'Snapshot In Progress'), ('snapshot_delivered', 'Snapshot Delivered'), ('walkthrough_scheduled', 'Walkthrough Scheduled'), ('active_pilot', 'Active Pilot'), ('pilot_complete', 'Pilot Complete')], default='waitlist', max_length=40)),
                ('mission', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('year_founded', models.CharField(blank=True, default='', max_length=50)),
                ('annual_budget_range', models.CharField(blank=True, default='', max_length=100)),
                ('team_size', models.CharField(blank=True, default='', max_length=100)),
                ('primary_programs', models.TextField(blank=True, default='')),
                ('communities_served', models.TextField(blank=True, default='')),
                ('current_initiatives', models.TextField(blank=True, default='')),
                ('geographic_reach', models.TextField(blank=True, default='')),
                ('current_revenue_sources', models.TextField(blank=True, default='')),
                ('grant_experience', models.TextField(blank=True, default='')),
                ('major_funders', models.TextField(blank=True, default='')),
                ('fundraising_activities', models.TextField(blank=True, default='')),
                ('funding_challenges', models.TextField(blank=True, default='')),
                ('key_partners', models.TextField(blank=True, default='')),
                ('community_relationships', models.TextField(blank=True, default='')),
                ('strategic_relationships', models.TextField(blank=True, default='')),
                ('government_relationships', models.TextField(blank=True, default='')),
                ('corporate_relationships', models.TextField(blank=True, default='')),
                ('top_goals', models.TextField(blank=True, default='')),
                ('biggest_challenges', models.TextField(blank=True, default='')),
                ('desired_outcomes', models.TextField(blank=True, default='')),
                ('success_definition', models.TextField(blank=True, default='')),
                ('strategic_plan', models.FileField(blank=True, default='', upload_to='pilot_documents/')),
                ('annual_report', models.FileField(blank=True, default='', upload_to='pilot_documents/')),
                ('grant_materials', models.FileField(blank=True, default='', upload_to='pilot_documents/')),
                ('program_information', models.FileField(blank=True, default='', upload_to='pilot_documents/')),
                ('other_documents', models.FileField(blank=True, default='', upload_to='pilot_documents/')),
                ('document_notes', models.TextField(blank=True, default='')),
                ('snapshot_status', models.CharField(choices=[('intake_complete', 'Intake Complete'), ('reviewing_organization', 'Reviewing Organization'), ('building_opportunity_web', 'Building Opportunity Web'), ('building_snapshot', 'Building Snapshot'), ('internal_review', 'Internal Review'), ('ready_for_delivery', 'Ready For Delivery'), ('delivered', 'Delivered')], default='reviewing_organization', max_length=40)),
                ('assigned_reviewer', models.CharField(blank=True, default='', max_length=300)),
                ('snapshot_notes', models.TextField(blank=True, default='')),
                ('snapshot_delivery_date', models.DateField(blank=True, null=True)),
                ('internal_comments', models.TextField(blank=True, default='')),
                ('walkthrough_status', models.CharField(choices=[('not_scheduled', 'Not Scheduled'), ('requested', 'Requested'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='not_scheduled', max_length=30)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('meeting_notes', models.TextField(blank=True, default='')),
                ('follow_up_actions', models.TextField(blank=True, default='')),
                ('recommended_next_steps', models.TextField(blank=True, default='')),
                ('action_plan_started', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilot_profile', to='core.project')),
                ('signup', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_profile', to='signals.interestsignup')),
            ],
            options={
                'ordering': ('organization_name', 'email'),
            },
        ),
        migrations.CreateModel(
            name='PilotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_valuable', models.TextField()),
                ('confusing', models.TextField(blank=True, default='')),
                ('indispensable', models.TextField(blank=True, default='')),
                ('would_recommend', models.CharField(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], default='maybe', max_length=20)),
                ('additional_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pilot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='signals.pilotprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
