# Generated by Django 6.0.6 on 2026-06-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_pilotprofile_pilotfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotprofile',
            name='lifecycle_status',
            field=models.CharField(choices=[('waitlist', 'Waitlist'), ('qualified', 'Qualified'), ('invited', 'Invited'), ('questionnaire_sent', 'Discovery Sent'), ('questionnaire_completed', 'Discovery Completed'), ('snapshot_in_progress', 'Snapshot In Progress'), ('snapshot_delivered', 'Snapshot Delivered'), ('walkthrough_scheduled', 'Walkthrough Scheduled'), ('active_pilot', 'Active Pilot'), ('pilot_complete', 'Pilot Complete')], default='waitlist', max_length=40),
        ),
    ]
