# Generated by Django 6.0.6 on 2026-06-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_alter_pilotprofile_lifecycle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotprofile',
            name='snapshot_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
