# Generated by Django 6.0.6 on 2026-06-21 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_budget_range_and_more'),
        ('signals', '0007_pilotprofile_snapshot_link'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationsourcepage',
            name='unique_organization_source_page',
        ),
        migrations.AddField(
            model_name='organizationsourcepage',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsourcepage',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organizationsourcepage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_materials', to='core.project'),
        ),
        migrations.AddField(
            model_name='organizationsourcepage',
            name='relevance',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationsourcepage',
            name='review_status',
            field=models.CharField(choices=[('new', 'New'), ('needs_review', 'Needs Review'), ('reviewed', 'Reviewed'), ('used_in_snapshot', 'Used In Snapshot'), ('archived', 'Archived')], default='new', max_length=30),
        ),
        migrations.AddField(
            model_name='organizationsourcepage',
            name='source_type',
            field=models.CharField(choices=[('website_page', 'Website Page'), ('annual_report', 'Annual Report'), ('strategic_plan', 'Strategic Plan'), ('grant_materials', 'Grant Materials'), ('program_description', 'Program Description'), ('funder_research', 'Funder Research'), ('partner_research', 'Partner Research'), ('founder_notes', 'Founder Notes'), ('other', 'Other')], default='website_page', max_length=40),
        ),
        migrations.AlterField(
            model_name='organizationsourcepage',
            name='url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='organizationsourcepage',
            constraint=models.UniqueConstraint(condition=models.Q(('url', ''), _negated=True), fields=('organization', 'url'), name='unique_organization_source_page'),
        ),
    ]
