# Generated by Django 6.0.6 on 2026-06-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0008_remove_organizationsourcepage_unique_organization_source_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='geography',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='mission_alignment_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='opportunity_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='relationship_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='source_references',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
