# Generated by Django 6.0.6 on 2026-06-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0009_partnerorganization_geography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestsignup',
            name='nurture_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
