# Generated by Django 6.0.6 on 2026-06-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0010_add_nurture_step_to_interest_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestsignup',
            name='research_brief',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
