# Generated by Django 6.0.6 on 2026-06-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0011_add_research_brief_to_interest_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('organization', models.CharField(blank=True, default='', max_length=300)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('source', models.CharField(choices=[('warm', 'Warm'), ('cold', 'Cold'), ('referral', 'Referral'), ('inbound', 'Inbound (Waitlist)')], default='warm', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('reached_out', 'Reached Out'), ('call_scheduled', 'Call Scheduled'), ('call_done', 'Call Done'), ('closed', 'Closed — Won'), ('nurturing', 'Nurturing'), ('passed', 'Passed')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('outreach_draft', models.TextField(blank=True, default='')),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('status', '-updated_at'),
            },
        ),
    ]
