# Generated by Django 6.0.6 on 2026-06-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_add_sales_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestsignup',
            name='interest_type',
            field=models.CharField(choices=[('opportunity_web_snapshot', 'Get Opportunity Web Snapshot'), ('founding_atlas_partners', 'Join Founding Atlas Partners'), ('newsletter_updates', 'Newsletter / Updates'), ('partnership_inquiry', 'Partnership Inquiry'), ('question', 'Question / Request Info')], default='opportunity_web_snapshot', max_length=40),
        ),
    ]
