# Generated by Django 6.0.6 on 2026-07-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0013_alter_interestsignup_interest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='email_status',
            field=models.CharField(blank=True, default='not_sent', max_length=30),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='focus_area',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='list_segment',
            field=models.CharField(choices=[('warm', 'Warm Network'), ('cold_florida_crm', 'Cold — Florida CRM')], default='warm', max_length=20),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='region',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='subject_line',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='warmth',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('reconnect', 'Reconnect'), ('cold', 'Cold')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='why_fit',
            field=models.TextField(blank=True, default=''),
        ),
    ]
