# Generated by Django 6.0.6 on 2026-07-03 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0014_saleslead_email_status_saleslead_focus_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyRollout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=120, unique=True)),
                ('rollout_tier', models.CharField(blank=True, default='', max_length=60)),
                ('region', models.CharField(blank=True, default='', max_length=120)),
                ('owner', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(blank=True, default='', max_length=60)),
                ('nonprofit_count', models.IntegerField(default=0)),
                ('high_priority_count', models.IntegerField(default=0)),
                ('funder_starter_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('county',),
            },
        ),
        migrations.CreateModel(
            name='FloridaOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=20, unique=True)),
                ('ein', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('sort_name', models.CharField(blank=True, default='', max_length=300)),
                ('street', models.CharField(blank=True, default='', max_length=300)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('county', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('region', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=10)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('subsection', models.CharField(blank=True, default='', max_length=10)),
                ('ntee_code', models.CharField(blank=True, default='', max_length=20)),
                ('ntee_sector', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('ruling_month', models.CharField(blank=True, default='', max_length=10)),
                ('asset_amount', models.BigIntegerField(blank=True, null=True)),
                ('income_amount', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promoted_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='florida_orgs', to='signals.saleslead')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
