# Generated by Django 6.0.6 on 2026-07-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0015_countyrollout_floridaorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='floridaorg',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='floridaorg',
            name='contact_source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='floridaorg',
            name='contact_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floridaorg',
            name='next_action',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='floridaorg',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='floridaorg',
            name='principal_officer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='floridaorg',
            name='priority',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='floridaorg',
            name='relationship_stage',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='floridaorg',
            name='website',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
