# Generated by Django 6.0.6 on 2026-07-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0016_floridaorg_contact_email_floridaorg_contact_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floridaorg',
            name='service_area',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
    ]
