# Generated by Django 6.0.6 on 2026-07-05 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_project_share_token'),
        ('signals', '0017_floridaorg_service_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opportunity', 'Opportunity'), ('funder', 'Funder'), ('partner', 'Partner'), ('resource', 'Resource'), ('government', 'Government')], max_length=20)),
                ('target_key', models.CharField(db_index=True, max_length=300)),
                ('verdict', models.CharField(choices=[('not_a_fit', 'Not a fit')], default='not_a_fit', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_feedback', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_feedback', to='core.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'kind', 'target_key'), name='unique_project_match_feedback')],
            },
        ),
    ]
