# Generated by Django 6.0.6 on 2026-07-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0018_matchfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslead',
            name='list_segment',
            field=models.CharField(choices=[('warm', 'Warm Network'), ('cold_florida_crm', 'Cold — Florida CRM'), ('cold_call_list', 'Cold — Call List')], default='warm', max_length=20),
        ),
    ]
