# Generated by Django 6.0.6 on 2026-07-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0019_saleslead_call_list_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='cc_emails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
