# Generated by Django 6.0.6 on 2026-07-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0020_saleslead_cc_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='outreach_outcome',
            field=models.CharField(blank=True, choices=[('awaiting', 'Awaiting reply'), ('replied', 'Replied'), ('interested', 'Interested'), ('meeting', 'Meeting booked'), ('not_interested', 'Not interested'), ('bounced', 'Bounced / bad email')], default='', max_length=20),
        ),
    ]
