# Generated by Django 6.0.6 on 2026-08-12 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0021_saleslead_outreach_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(default='link', help_text='How it was recorded: link, reply, manual.', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Email opt-out',
                'ordering': ('-created_at',),
            },
        ),
    ]
