# Generated by Django 6.0.6 on 2026-08-12 20:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_excluded_beneficiaries'),
        ('signals', '0022_emailoptout'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('cold_opener', 'Cold opener'), ('cold_followup', 'Cold follow-up'), ('warm', 'Warm outreach')], default='cold_opener', max_length=20)),
                ('sequence_position', models.PositiveSmallIntegerField(default=1, help_text='1 = opener, 2 = first follow-up, and so on.')),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('primary_angle', models.CharField(blank=True, choices=[('federal_funding', 'Federal funding'), ('federal_program_pathway', 'Federal program pathway'), ('grants_gov_match', 'Grants.gov match'), ('state_funding', 'State funding'), ('county_funding', 'County funding'), ('city_funding', 'City funding'), ('agency_program', 'Agency program'), ('contract_expiration', 'Contract expiration'), ('intermediary_structure', 'Intermediary structure'), ('procurement_pathway', 'Procurement pathway'), ('partnership_pathway', 'Partnership pathway'), ('community_partner_resource', 'Community partner resource'), ('government_referral_pathway', 'Government referral pathway'), ('agency_relationship', 'Agency relationship'), ('institutional_partner', 'Institutional partner'), ('free_resource', 'Free resource'), ('low_cost_resource', 'Low-cost resource'), ('technical_assistance', 'Technical assistance'), ('capacity_building_resource', 'Capacity-building resource'), ('training_resource', 'Training resource'), ('technology_resource', 'Technology resource'), ('facility_or_space_resource', 'Facility or space resource'), ('workforce_resource', 'Workforce resource'), ('volunteer_resource', 'Volunteer resource'), ('in_kind_resource', 'In-kind resource'), ('data_or_research_resource', 'Data or research resource'), ('readiness_gap', 'Readiness gap'), ('application_readiness', 'Application readiness'), ('compliance_readiness', 'Compliance readiness'), ('fragmented_research', 'Fragmented research'), ('category_mechanism', 'Category-level mechanism'), ('school_specific_resource', 'School-specific resource'), ('unclassified', 'Unclassified')], default='', help_text='Why the reader might care — the reason, not the source.', max_length=40)),
                ('angle_detail', models.CharField(blank=True, default='', help_text="The concrete argument, e.g. 'CINS/FINS contract through 2026-06-30'.", max_length=300)),
                ('personalization', models.CharField(blank=True, choices=[('personalized', 'Personalized'), ('category_relevant', 'Category-relevant')], default='', help_text='Honest classification — category-relevant is legitimate, and must not be dressed up as research.', max_length=20)),
                ('evidence_ref', models.CharField(blank=True, default='', help_text='Where the recipient-specific claim came from, when the research layer exposes an identifier. Free-text until it does.', max_length=200)),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('sent', 'Sent'), ('send_failed', 'Send failed')], default='drafted', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('send_error', models.TextField(blank=True, default='')),
                ('message_id', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_messages', to='core.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='signals.saleslead')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['lead', '-created_at'], name='signals_out_lead_id_428e0d_idx')],
            },
        ),
    ]
