# Generated by Django 6.0.6 on 2026-08-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0023_outreachmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='disposition',
            field=models.CharField(choices=[('eligible', 'Eligible'), ('review', 'Needs review'), ('disqualified', 'Disqualified from this campaign')], db_index=True, default='eligible', max_length=20),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='disposition_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='disposition_detail',
            field=models.TextField(blank=True, default='', help_text='Human-readable explanation and its evidence.'),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='disposition_reason',
            field=models.CharField(blank=True, choices=[('organization_closed', 'Organization closed'), ('organization_inactive', 'Organization inactive'), ('wrong_organization_type', 'Wrong organization type'), ('wrong_geography', 'Outside campaign geography'), ('already_customer', 'Already a customer'), ('already_suppressed', 'Suppressed / do-not-contact'), ('outside_campaign_criteria', 'Outside campaign criteria'), ('contact_left_organization', 'Contact left the organization'), ('contact_role_inappropriate', 'Contact role inappropriate'), ('duplicate_existing_relationship', 'Duplicate of an existing relationship'), ('insufficient_relevance', 'Campaign proposition not relevant'), ('conflicting_research', 'Sources conflict'), ('stale_research', 'Research too old to act on'), ('needs_human_review', 'Needs human review')], default='', help_text='Machine-readable reason — queryable, so exclusions can be audited.', max_length=40),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='disposition_scope',
            field=models.CharField(blank=True, default='', help_text="'organization' or 'contact'. A departed contact does not close the org.", max_length=20),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='disposition_source',
            field=models.CharField(blank=True, default='', help_text="'automatic' or 'human' — whether a person confirmed this.", max_length=20),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='evidence_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='operator_notes',
            field=models.TextField(blank=True, default='', help_text='Operator commentary. Workflow only — never treated as a fact about the org.'),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='relationship_context',
            field=models.TextField(blank=True, default='', help_text='Approved relationship history for warm outreach — a separate authority level from research, passed to the writer under its own heading.'),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='research_profile',
            field=models.TextField(blank=True, default='', help_text='Verified research, approved for use as recipient evidence in copy.'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Legacy mixed notes. Not used as writer evidence — see research_profile.'),
        ),
    ]
