# Generated by Django 6.0.6 on 2026-08-13 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0024_saleslead_disposition_saleslead_disposition_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.EmailField(max_length=254, unique=True)),
                ('history_id', models.CharField(blank=True, default='', max_length=40)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.EmailField(help_text='Which configured mailbox this was observed in.', max_length=254)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound_human', 'Outbound (human, from Gmail)')], default='inbound', max_length=20)),
                ('classification', models.CharField(choices=[('human_reply_unclassified', 'Human reply (unclassified)'), ('removal_request', 'Removal request'), ('autoresponder', 'Autoresponder / out-of-office'), ('bounce_hard', 'Hard bounce'), ('bounce_soft', 'Soft / temporary delivery failure'), ('dsn_unresolved', 'Delivery notification (unresolved)'), ('outbound_human', "Marcus's own reply")], max_length=40)),
                ('correlation', models.CharField(choices=[('in_reply_to', 'Exact In-Reply-To'), ('references', 'Exact References'), ('thread', 'Provider thread'), ('address_fallback', 'Address + recency fallback'), ('unresolved', 'Unresolved')], default='unresolved', max_length=20)),
                ('gmail_id', models.CharField(max_length=64)),
                ('thread_id', models.CharField(blank=True, default='', max_length=64)),
                ('rfc_message_id', models.CharField(blank=True, default='', max_length=300)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=300)),
                ('references_header', models.TextField(blank=True, default='')),
                ('from_address', models.CharField(blank=True, default='', max_length=320)),
                ('to_addresses', models.CharField(blank=True, default='', max_length=500)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('header_date', models.DateTimeField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True, default='', help_text='Normalized plain text, capped at ingest.')),
                ('needs_attention', models.BooleanField(db_index=True, default=False)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='signals.saleslead')),
                ('outreach_message', models.ForeignKey(blank=True, help_text='The Atlas touch this event answers — per-message attribution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='signals.outreachmessage')),
            ],
            options={
                'ordering': ('-ingested_at',),
                'constraints': [models.UniqueConstraint(fields=('mailbox', 'gmail_id'), name='uniq_inbound_mailbox_gmail_id')],
            },
        ),
    ]
