# Generated by Django 6.0.6 on 2026-08-13 21:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0025_mailboxcursor_inboundmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachmessage',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('sending', 'Sending (claimed)'), ('sent', 'Sent'), ('send_failed', 'Send failed')], default='drafted', max_length=20),
        ),
        migrations.CreateModel(
            name='RunnerDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=40)),
                ('mode', models.CharField(default='shadow', max_length=10)),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('reason', models.TextField(blank=True, default='')),
                ('would_send_subject', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_decisions', to='signals.saleslead')),
                ('outreach_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_decisions', to='signals.outreachmessage')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
