# Generated by Django 6.0.6 on 2026-07-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_deal_email_routing'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_intel',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
