"""Gap 3A: the outbound path is safe and reply-correlatable.

Four blockers from the architecture audit, fixed in signals/outreach.py:
1. the RFC Message-ID was generated by Django (anchored to the container
   hostname) and discarded — now minted by us, domain-anchored, stored;
2. send failures left no trace — SEND_FAILED/send_error were dead code;
3. outreach_outcome controlled nothing — a lead who said "not interested"
   could be drafted and sent to again;
4. double-send protection was a check-then-act race on lead.email_status.

Behavior tests, not implementation tests.
"""
from __future__ import annotations

import smtplib

import pytest
from django.core import mail
from django.urls import reverse

from openoutreach.signals.models import OutreachAngle, OutreachMessage, SalesLead
from openoutreach.signals.outreach import send_outreach_email

pytestmark = pytest.mark.django_db


@pytest.fixture
def staff(db):
    from django.contrib.auth import get_user_model
    return get_user_model().objects.create_user(username="ops", password="x", is_staff=True)


@pytest.fixture(autouse=True)
def _from_mail(settings):
    settings.DEFAULT_FROM_EMAIL = "mail@anansiatlas.com"


def _lead(**kw):
    return SalesLead.objects.create(**{
        "name": "Dana Reed", "organization": "Brightpaths", "email": "dana@brightpaths.org",
        "email_status": "not_sent", "list_segment": SalesLead.Segment.COLD_FLORIDA_CRM,
        **kw,
    })


def _post_send(client, staff, lead, subject="hi", body="b"):
    client.force_login(staff)
    return client.post(reverse("operator-outreach-send", kwargs={"pk": lead.pk}),
                       {"subject": subject, "body": body})


class _RaisingEmailMessage:
    """Stands in for EmailMessage so a chosen exception fires on .send()."""

    def __init__(self, exc):
        self.exc = exc

    def __call__(self, *args, **kwargs):
        self.kwargs = kwargs
        return self

    def send(self, fail_silently=False):
        raise self.exc


# ── 1-3. Message-ID lifecycle ───────────────────────────────────────────────

def test_message_id_is_minted_and_domain_anchored():
    lead = _lead()
    send_outreach_email(lead, "hi", "b")
    msg = OutreachMessage.objects.get(lead=lead)
    # Minted, RFC-shaped, anchored to the sender's domain — not the container
    # hostname Django would have used.
    assert msg.message_id.startswith("<") and msg.message_id.endswith(">")
    assert msg.message_id.rstrip(">").endswith("anansiatlas.com")


def test_wire_header_and_stored_value_are_identical():
    lead = _lead()
    send_outreach_email(lead, "hi", "b")
    sent = mail.outbox[0]
    stored = OutreachMessage.objects.get(lead=lead).message_id
    # The exact ID on the wire is the one in the database — this equality is what
    # inbound In-Reply-To/References correlation will depend on.
    assert sent.extra_headers["Message-ID"] == stored


def test_message_id_is_minted_before_the_smtp_call(mocker):
    # Even when the send fails, the identity must already be durable — an
    # ambiguous timeout may have delivered the mail carrying this ID.
    lead = _lead()
    mocker.patch("openoutreach.signals.outreach.EmailMessage",
                 _RaisingEmailMessage(TimeoutError("read timed out")))
    with pytest.raises(TimeoutError):
        send_outreach_email(lead, "hi", "b")
    msg = OutreachMessage.objects.get(lead=lead)
    assert msg.message_id  # persisted despite the failure


def test_retry_after_failure_reuses_the_same_message_id(mocker):
    lead = _lead()
    mocker.patch("openoutreach.signals.outreach.EmailMessage",
                 _RaisingEmailMessage(TimeoutError("read timed out")))
    with pytest.raises(TimeoutError):
        send_outreach_email(lead, "hi", "b")
    first_id = OutreachMessage.objects.get(lead=lead).message_id
    mocker.stopall()
    send_outreach_email(lead, "hi", "b")  # the retry, now succeeding
    msg = OutreachMessage.objects.get(lead=lead)  # same row, not a second one
    assert msg.message_id == first_id
    assert mail.outbox[0].extra_headers["Message-ID"] == first_id
    assert msg.status == OutreachMessage.Status.SENT


# ── 4-8. failure persistence ────────────────────────────────────────────────

def test_successful_send_marks_sent():
    lead = _lead()
    send_outreach_email(lead, "hi", "b")
    msg = OutreachMessage.objects.get(lead=lead)
    assert msg.status == OutreachMessage.Status.SENT
    assert msg.sent_at is not None
    assert msg.send_error == ""


@pytest.mark.parametrize("exc", [
    smtplib.SMTPRecipientsRefused({"dana@brightpaths.org": (550, b"user unknown")}),
    ConnectionRefusedError("connection refused"),
    TimeoutError("read timed out"),
])
def test_smtp_failure_is_persisted(mocker, exc):
    lead = _lead()
    mocker.patch("openoutreach.signals.outreach.EmailMessage", _RaisingEmailMessage(exc))
    with pytest.raises(type(exc)):
        send_outreach_email(lead, "hi", "b")
    msg = OutreachMessage.objects.get(lead=lead)
    assert msg.status == OutreachMessage.Status.SEND_FAILED
    assert msg.sent_at is None
    assert type(exc).__name__ in msg.send_error
    assert len(msg.send_error) <= 500


def test_ambiguous_timeout_is_marked_as_possibly_delivered(mocker):
    # SMTP can accept the DATA and the response still be lost. That failure class
    # is recorded distinctly, and the policy is hold-for-human, not auto-retry.
    lead = _lead()
    mocker.patch("openoutreach.signals.outreach.EmailMessage",
                 _RaisingEmailMessage(TimeoutError("read timed out")))
    with pytest.raises(TimeoutError):
        send_outreach_email(lead, "hi", "b")
    msg = OutreachMessage.objects.get(lead=lead)
    assert msg.send_error.startswith("AMBIGUOUS")
    assert "same Message-ID" in msg.send_error


def test_recipient_refusal_is_not_marked_ambiguous(mocker):
    # A 550 is a definitive no — the mail was not delivered.
    lead = _lead()
    exc = smtplib.SMTPRecipientsRefused({"dana@brightpaths.org": (550, b"user unknown")})
    mocker.patch("openoutreach.signals.outreach.EmailMessage", _RaisingEmailMessage(exc))
    with pytest.raises(smtplib.SMTPRecipientsRefused):
        send_outreach_email(lead, "hi", "b")
    assert not OutreachMessage.objects.get(lead=lead).send_error.startswith("AMBIGUOUS")


def test_failed_send_does_not_mark_lead_sent_or_advance_state(mocker):
    lead = _lead()
    mocker.patch("openoutreach.signals.outreach.EmailMessage",
                 _RaisingEmailMessage(ConnectionRefusedError("nope")))
    with pytest.raises(ConnectionRefusedError):
        send_outreach_email(lead, "hi", "b")
    lead.refresh_from_db()
    assert lead.email_status == "not_sent"
    assert lead.status == SalesLead.Status.NEW          # not advanced
    assert lead.outreach_outcome == ""                   # no follow-up timer basis


def test_send_error_contains_no_credentials(mocker, settings):
    settings.EMAIL_HOST_PASSWORD = "supersecret-app-password"
    lead = _lead()
    exc = smtplib.SMTPAuthenticationError(535, b"5.7.8 auth rejected")
    mocker.patch("openoutreach.signals.outreach.EmailMessage", _RaisingEmailMessage(exc))
    with pytest.raises(smtplib.SMTPAuthenticationError):
        send_outreach_email(lead, "hi", "b")
    assert "supersecret" not in OutreachMessage.objects.get(lead=lead).send_error


def test_later_success_clears_stale_failure_state(mocker):
    lead = _lead()
    mocker.patch("openoutreach.signals.outreach.EmailMessage",
                 _RaisingEmailMessage(ConnectionRefusedError("nope")))
    with pytest.raises(ConnectionRefusedError):
        send_outreach_email(lead, "hi", "b")
    mocker.stopall()
    send_outreach_email(lead, "hi", "b")
    msg = OutreachMessage.objects.get(lead=lead)
    assert msg.status == OutreachMessage.Status.SENT
    assert msg.send_error == ""


def test_failed_send_preserves_the_drafted_angle(mocker):
    # A failure must not cost the message its recorded argument.
    lead = _lead()
    OutreachMessage.objects.create(lead=lead, subject="hi", body="b",
                                   primary_angle=OutreachAngle.COUNTY_FUNDING)
    mocker.patch("openoutreach.signals.outreach.EmailMessage",
                 _RaisingEmailMessage(ConnectionRefusedError("nope")))
    with pytest.raises(ConnectionRefusedError):
        send_outreach_email(lead, "hi", "b")
    msg = OutreachMessage.objects.get(lead=lead)
    assert msg.primary_angle == OutreachAngle.COUNTY_FUNDING
    assert msg.status == OutreachMessage.Status.SEND_FAILED


# ── 9-12. terminal outcomes ─────────────────────────────────────────────────

@pytest.mark.parametrize("outcome", [SalesLead.Outcome.NOT_INTERESTED,
                                     SalesLead.Outcome.MEETING,
                                     SalesLead.Outcome.BOUNCED])
def test_terminal_outcomes_block_a_future_cold_send(client, staff, outcome):
    lead = _lead(email_status="sent", outreach_outcome=outcome)
    OutreachMessage.objects.create(lead=lead, subject="new", body="new touch")
    _post_send(client, staff, lead, subject="new", body="new touch")
    assert mail.outbox == []


def test_closed_won_blocks_acquisition_outreach(client, staff):
    lead = _lead(status=SalesLead.Status.CLOSED)
    _post_send(client, staff, lead)
    assert mail.outbox == []


def test_open_conversation_holds_automated_followup_but_not_a_human_send():
    # replied/interested = a live thread. Automated follow-up drafting pauses;
    # a human sending by hand is still allowed — this is not suppression.
    lead = _lead(email_status="sent", outreach_outcome=SalesLead.Outcome.REPLIED)
    assert lead.followup_hold() != ""
    assert lead.cold_outreach_block() == ""      # the send gate does not block
    send_outreach_email(lead, "a human reply", "written by hand")
    assert len(mail.outbox) == 1


def test_awaiting_outcome_blocks_nothing():
    lead = _lead(email_status="sent", outreach_outcome=SalesLead.Outcome.AWAITING)
    assert lead.cold_outreach_block() == ""
    assert lead.followup_hold() == ""


def test_optout_and_outcome_and_disqualification_stay_distinct():
    # opt-out = global suppression; not_interested = this sequence is over;
    # disqualification = campaign fit. None implies the others.
    from openoutreach.signals.models import EmailOptOut

    lead = _lead(outreach_outcome=SalesLead.Outcome.NOT_INTERESTED)
    assert not EmailOptOut.objects.filter(email=lead.email).exists()
    assert lead.disposition == SalesLead.DISPOSITION_ELIGIBLE
    assert "not interested" in lead.cold_outreach_block()


# ── 13. concurrency ─────────────────────────────────────────────────────────

def test_the_same_message_cannot_be_delivered_twice():
    # The in-transaction duplicate check: once a subject+body pair is SENT, a
    # second attempt at the identical message refuses. Combined with the
    # select_for_update lead lock (which serializes concurrent attempts so the
    # second always sees the first's committed SENT row), this is the invariant;
    # true parallel execution is not exercisable on the sqlite test database.
    lead = _lead()
    send_outreach_email(lead, "hi", "b")
    with pytest.raises(ValueError, match="already sent"):
        send_outreach_email(lead, "hi", "b")
    assert len(mail.outbox) == 1


def test_a_genuinely_new_touch_is_not_blocked_as_a_duplicate():
    lead = _lead()
    send_outreach_email(lead, "hi", "first touch")
    send_outreach_email(lead, "another angle", "second touch, different body")
    assert len(mail.outbox) == 2
    positions = list(OutreachMessage.objects.filter(lead=lead)
                     .order_by("sequence_position")
                     .values_list("sequence_position", flat=True))
    assert positions == [1, 2]


def test_followups_are_now_sendable_from_the_cockpit(client, staff):
    # Pre-existing bug surfaced by the audit: the view's per-lead "already
    # emailed" check made every second touch unsendable. A drafted new touch
    # now passes the view; per-message protection lives in send_outreach_email.
    lead = _lead()
    send_outreach_email(lead, "opener", "first")
    OutreachMessage.objects.create(
        lead=lead, subject="follow-up", body="second touch",
        genre=OutreachMessage.Genre.COLD_FOLLOWUP, sequence_position=2)
    _post_send(client, staff, lead, subject="follow-up", body="second touch")
    assert len(mail.outbox) == 2


def test_double_click_on_the_same_draft_sends_once(client, staff):
    lead = _lead()
    OutreachMessage.objects.create(lead=lead, subject="hi", body="b")
    _post_send(client, staff, lead)
    _post_send(client, staff, lead)   # the second click
    assert len(mail.outbox) == 1


# ── 14-15. no regressions ───────────────────────────────────────────────────

def test_optout_still_blocks_and_leaves_no_sent_record(client, staff):
    from openoutreach.signals.unsubscribe import record_opt_out

    lead = _lead()
    record_opt_out(lead.email)
    _post_send(client, staff, lead)
    assert mail.outbox == []
    assert not OutreachMessage.objects.filter(
        lead=lead, status=OutreachMessage.Status.SENT).exists()


def test_gate_refusal_is_not_recorded_as_a_send_failure():
    # A refused send never attempted delivery; recording SEND_FAILED would make
    # the audit trail claim an SMTP attempt that did not happen.
    lead = _lead()
    lead.set_disposition("organization_closed")
    lead.save()
    with pytest.raises(ValueError):
        send_outreach_email(lead, "hi", "b")
    assert not OutreachMessage.objects.filter(lead=lead).exists()


def test_sent_messages_still_carry_their_angle_for_the_followup_prompt():
    lead = _lead()
    OutreachMessage.objects.create(lead=lead, subject="hi", body="b",
                                   primary_angle=OutreachAngle.FREE_RESOURCE)
    send_outreach_email(lead, "hi", "b")
    prev = OutreachMessage.last_for(lead, sent_only=True)
    assert prev.primary_angle == OutreachAngle.FREE_RESOURCE
    assert prev.message_id
