# Generated by Django 6.0.6 on 2026-06-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='budget_range',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='current_funding_sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organization',
            name='existing_partnerships',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
