# Generated by Django 6.0.6 on 2026-06-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organizationmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='has_toured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='visited_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
