# Generated by Django 6.0.6 on 2026-06-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='contact_position',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='intake_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
