# Generated by Django 6.0.6 on 2026-06-30 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_set_site_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='share_token',
        ),
    ]
