# Generated by Django 6.0.6 on 2026-07-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_project_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='page_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
