# Generated by Django 6.0.6 on 2026-07-05 14:15

from django.db import migrations, models


def backfill_seat_authority(apps, schema_editor):
    """Existing installs: every project user gets a member row (invited seats
    never got one), and each project's first seat becomes the account admin."""
    Project = apps.get_model("core", "Project")
    OrganizationMember = apps.get_model("core", "OrganizationMember")

    for project in Project.objects.all():
        for user in project.users.all():
            OrganizationMember.objects.get_or_create(user=user, project=project)
        members = list(OrganizationMember.objects.filter(project=project).order_by("created_at", "pk"))
        if not members or any(m.is_admin for m in members):
            continue
        admin = next((m for m in members if m.role == "owner"), members[0])
        admin.is_admin = True
        admin.save(update_fields=["is_admin"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_member_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='excluded_focus_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='organization',
            name='website_check',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_seat_authority, migrations.RunPython.noop),
    ]
