# Generated by Django 6.0.6 on 2026-07-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seat_authority_focus_exclusions_website_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='excluded_beneficiaries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
