# Generated by Django 6.0.6 on 2026-07-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_excluded_beneficiaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tier',
            field=models.CharField(choices=[('full', 'Full Seat'), ('snapshot', 'Snapshot')], default='full', help_text='full = interactive workspace; snapshot = read-only monthly Snapshot tier.', max_length=20),
        ),
    ]
